import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import UserContextProvider from "@/context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserContextProvider>
        <body className={`${inter.className} h-screen w-screen bg-neutral-100`}>
          <Header/>
          <main className="h-[85vh] bg-white">
            {children}
          </main>
        </body>
        </UserContextProvider>
    </html>
  );
}
